In [9]:
from google.colab import files
uploaded = files.upload()

Saving Student.csv to Student.csv

In [10]:
''' Import the Pandas library using its standard alias.
Write the Python statement required to import the Pandas library so that it can be
referenced as 'pd' in your workflows.'''
import pandas as pd

In [11]:
''' Create a Pandas Series from a List.
Given a Python list `data = [100, 200, 300, 400]`, write the code to convert it into a baseline
Pandas Series and print it. '''
import pandas as pd

data = [100, 200, 300, 400]

series = pd.Series(data)

print(series)

0    100
1    200
2    300
3    400
dtype: int64

In [12]:
''' Create a DataFrame from a Dictionary.
Given a dictionary representing user details:
`user_dict = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}`
Write the code to create a Pandas DataFrame from this dictionary.'''
import pandas as pd
user_dict = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df = pd.DataFrame(user_dict)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [13]:
'''  Read a structured CSV file.
Write down the specific Pandas function used to load an external file named `'dataset.csv'`
into a DataFrame variable called `df`.'''
import pandas as pd

df = pd.read_csv("dataset.csv")

In [14]:
''' Inspect the first few rows of a DataFrame.
Given a large DataFrame `df`, write the command to display only the top 5 rows of data to
quickly inspect its structure. '''
import pandas as pd

df = pd.read_csv("dataset.csv")
df.head(5)

   ID                 Name  Age Department  Salary
0   1          James Smith   63         HR   65565
1   2           Alex Moore   56         IT  107904
2   3  Elizabeth Hernandez   38         HR  113279
3   4       Jessica Miller   40  Marketing   95913
4   5       Patricia Brown   34         HR  104971

In [15]:
''' View DataFrame metadata and shape.
Write the commands to check: (a) The exact dimensions (number of rows and columns) of a
DataFrame, and (b) A summary of columns, non-null counts, and data types.'''
import pandas as pd

df = pd.read_csv("dataset.csv")
print(df.shape)

print(df.info())

(20, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          20 non-null     int64
 1   Name        20 non-null     object
 2   Age         20 non-null     int64
 3   Department  20 non-null     object
 4   Salary      20 non-null     int64
dtypes: int64(3), object(2)
memory usage: 932.0+ bytes
None

In [16]:
''' Selecting a single column from a DataFrame.
Given a DataFrame `df` with columns `['Product', 'Price', 'Quantity']`, write a command to
select and extract only the `'Price'` column as a Series.'''
import pandas as pd

df = pd.DataFrame({
    "Product": ["Laptop", "Phone", "Tablet"],
    "Price": [50000, 30000, 20000],
    "Quantity": [5, 10, 8]
})

price_series = df["Price"]

print(price_series)

0    50000
1    30000
2    20000
Name: Price, dtype: int64

In [17]:
''' Filtering data based on a structural condition.
Given a DataFrame `df` with a column named `'Salary'`, write code to filter and return a new
DataFrame containing only the rows where the salary is greater than `50000`.'''
import pandas as pd

df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Karan", "Neha"],
    "Salary": [45000, 60000, 55000, 40000]
})

filtered_df = df[df["Salary"] > 50000]

print(filtered_df)

    Name  Salary
1   Riya   60000
2  Karan   55000

In [18]:
''' Calculate descriptive summary statistics.
Write a single built-in Pandas method that automatically generates a statistical summary
(mean, standard deviation, min, max, etc.) for all numerical columns in a DataFrame.'''
import pandas as pd

df = pd.DataFrame({
    "Age": [20, 22, 25, 21],
    "Salary": [50000, 60000, 55000, 70000]
})

print(df.describe())

             Age        Salary
count   4.000000      4.000000
mean   22.000000  58750.000000
std     2.160247   8539.125638
min    20.000000  50000.000000
25%    20.750000  53750.000000
50%    21.500000  57500.000000
75%    22.750000  62500.000000
max    25.000000  70000.000000

In [4]:
''' Exporting a modified DataFrame.
You have finished transforming a DataFrame named `clean_df`. Write the syntax required to
save this object back onto your computer disk as a new CSV file named `'output.csv'`
without saving the row numbers/indices.'''
import pandas as pd
clean_df = pd.DataFrame({
    "Name": ["Aarav", "Ananya", "Vihaan"],
    "Age": [21, 20, 22],
    "Salary": [55000, 60000, 48000]
})

print(clean_df)

# Save to a new CSV file without row indices
clean_df.to_csv("output.csv", index=False)

print("DataFrame saved as output.csv")

     Name  Age  Salary
0   Aarav   21   55000
1  Ananya   20   60000
2  Vihaan   22   48000
DataFrame saved as output.csv

In [19]:
''' Handling missing values (Intermediate).
Given a DataFrame `df` containing several missing values (`NaN` entries) in a column
named `'Score'`, write code to: (a) Drop all rows where `'Score'` is missing'''
import pandas as pd
import numpy as np

df = pd.read_csv("Gamescore.csv")
df_dropped = df.dropna(subset=["Score"])
print(df_dropped)

   ID    Name  Age  Score
0   1   Alice   25   85.0
1   2     Bob   30   92.0
3   4   David   35   78.0
4   5     Eva   28   88.0
6   7   Grace   24   95.0
7   8  Hannah   29   70.0

In [20]:

''' (b) In a
separate snippet, fill those missing values with the average (mean) value of that column
instead.'''
import pandas as pd
import numpy as np

df = pd.read_csv("Gamescore.csv")
#Fill missing values with the mean mileage i.e 18.857143
df["Score"] = df["Score"].fillna(df["Score"].mean())

print(df)

   ID     Name  Age      Score
0   1    Alice   25  85.000000
1   2      Bob   30  92.000000
2   3  Charlie   22  84.666667
3   4    David   35  78.000000
4   5      Eva   28  88.000000
5   6    Frank   40  84.666667
6   7    Grace   24  95.000000
7   8   Hannah   29  70.000000
8   9      Ian   31  84.666667

In [21]:
''' Grouping data and aggregating values (Intermediate).
You have a sales DataFrame `df` with columns `['Store', 'Product', 'Sales']`. Write code to
group the data by the `'Store'` column and calculate the total (sum) sales for each store.'''
import pandas as pd

df = pd.DataFrame({
    "Store": ["A", "A", "B", "B", "C"],
    "Product": ["Pen", "Book", "Pen", "Book", "Pen"],
    "Sales": [100, 200, 150, 250, 300]
})

total_sales = df.groupby("Store")["Sales"].sum()

print(total_sales)

Store
A    300
B    400
C    300
Name: Sales, dtype: int64

In [22]:
''' Merging two distinct DataFrames (Intermediate).
Given two DataFrames, `df_employees` (with columns `['Emp_ID', 'Name']`) and `df_salaries` (with columns `['Emp_ID', 'Salary']`).
 Write a Pandas statement to perform an inner join/merge on these DataFrames using their common column `'Emp_ID'`. '''
import pandas as pd

df_employees = pd.DataFrame({
    "Emp_ID": [101, 102, 103],
    "Name": ["Aarav", "Ananya", "Vihaan"]
})

df_salaries = pd.DataFrame({
    "Emp_ID": [101, 102, 104],
    "Salary": [50000, 60000, 55000]
})

merged_df = pd.merge(df_employees, df_salaries, on="Emp_ID", how="inner")

print(merged_df)

   Emp_ID    Name  Salary
0     101   Aarav   50000
1     102  Ananya   60000

In [23]:
''' Conditional column creation using vectorization (Intermediate).
Given a DataFrame `df` containing a numerical column `'Final_Score'`, write a statement
using Pandas or NumPy's conditional logic to create a brand new column named `'Status'`.
If `'Final_Score'` is 50 or above, the status should be `'Pass'`; otherwise, it should be `'Fail'''
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Final_Score": [75, 45, 60, 30, 50]
})

df["Status"] = np.where(df["Final_Score"] >= 50, "Pass", "Fail")

print(df)

   Final_Score Status
0           75   Pass
1           45   Fail
2           60   Pass
3           30   Fail
4           50   Pass

In [24]:
'''Setting and resetting structural indices (Intermediate).
Given a DataFrame `df` with a column named `'Employee_ID'`, convert this column to serve
as the structural row index of the DataFrame. Then, write a subsequent line of code that
completely reverses this action, returning the index back into a regular column.'''
import pandas as pd

df = pd.DataFrame({
    "Employee_ID": [101, 102, 103],
    "Name": ["Aarav", "Ananya", "Vihaan"]
})

# Set index
df = df.set_index("Employee_ID")
print(df)

# Reset index
df = df.reset_index()
print(df)

               Name
Employee_ID
101           Aarav
102          Ananya
103          Vihaan
   Employee_ID    Name
0          101   Aarav
1          102  Ananya
2          103  Vihaan

In [25]:
import pandas as pd

df = pd.read_csv("car_dataset_100.csv")
df[df["Company"].isin(["Toyota", "Honda"])] # only display honda or toyota cars
df.head(20)

    Car_ID        Company    Model Engine_Type Transmission  Price_INR
0        1         Toyota  Scorpio      Petrol    Automatic    2736015
1        2          Honda  Corolla    Electric    Automatic    3358822
2        3         Toyota    Creta      Diesel    Automatic    3300087
3        4           Tata    Creta      Petrol    Automatic    1234955
4        5            Kia       X5      Petrol       Manual    3146261
5        6  Mercedes-Benz    Civic      Petrol       Manual    1692650
6        7        Hyundai  Corolla      Hybrid    Automatic    4500723
7        8       Mahindra  C-Class      Petrol    Automatic    3381169
8        9           Audi  C-Class      Diesel    Automatic     605261
9       10            BMW       A4    Electric    Automatic    4867184
10      11            BMW  Mustang      Petrol       Manual    1192980
11      12  Mercedes-Benz  Scorpio      Diesel    Automatic    3326257
12      13           Audi       X5      Petrol    Automatic    3751891
13      14            Kia  Mustang      Petrol       Manual    1239516
14      15           Ford  Corolla      Hybrid       Manual    3903416
15      16           Audi       A4      Petrol    Automatic    4650511
16      17           Tata       A4    Electric       Manual    1789846
17      18           Audi  C-Class    Electric    Automatic     870188
18      19         Toyota    Creta    Electric       Manual     676234
19      20       Mahindra  Mustang      Hybrid    Automatic    4026212

In [26]:
# handling missing values
import pandas as pd
import numpy as np

df = pd.read_csv("car_dataset_100.csv")
df["Price_Lakh"] = df["Price_INR"] / 100000  #this is creating column using data that already exist
df["Mileage"] = [18, 20, np.nan, 15, 22, np.nan, 19, 17, np.nan, 21] * 10  # column with few missing values
df["Mileage"].isnull().sum()
df["Mileage"] = df["Mileage"].fillna(df["Mileage"].mean()) #Fill missing values with the mean mileage i.e 18.857143
df.head(15)

,Car_ID,Company,Model,Engine_Type,Transmission,Price_INR,Price_Lakh,Mileage
0,1,Toyota,Scorpio,Petrol,Automatic,2736015,27.36015,18.000000
1,2,Honda,Corolla,Electric,Automatic,3358822,33.58822,20.000000
2,3,Toyota,Creta,Diesel,Automatic,3300087,33.00087,18.857143
3,4,Tata,Creta,Petrol,Automatic,1234955,12.34955,15.000000
4,5,Kia,X5,Petrol,Manual,3146261,31.46261,22.000000
5,6,Mercedes-Benz,Civic,Petrol,Manual,1692650,16.92650,18.857143
6,7,Hyundai,Corolla,Hybrid,Automatic,4500723,45.00723,19.000000
7,8,Mahindra,C-Class,Petrol,Automatic,3381169,33.81169,17.000000
8,9,Audi,C-Class,Diesel,Automatic,605261,6.05261,18.857143
9,10,BMW,A4,Electric,Automatic,4867184,48.67184,21.000000
10,11,BMW,Mustang,Petrol,Manual,1192980,11.92980,18.000000
11,12,Mercedes-Benz,Scorpio,Diesel,Automatic,3326257,33.26257,20.000000
12,13,Audi,X5,Petrol,Automatic,3751891,37.51891,18.857143
13,14,Kia,Mustang,Petrol,Manual,1239516,12.39516,15.000000
14,15,Ford,Corolla,Hybrid,Manual,3903416,39.03416,22.000000

In [27]:
# adding or removing columns
import pandas as pd
import numpy as np

df = pd.read_csv("car_dataset_100.csv")
df["Price_Lakh"] = df["Price_INR"] / 100000  #this is creating column using data that already exist
df["Rating"] = [4,5,3,4,5] * 20
df["Mileage"] = [18, 20, np.nan, 15, 22, np.nan, 19, 17, np.nan, 21] * 10  # column with few missing values

df = df.drop("Rating", axis=1)
df.head()

,Car_ID,Company,Model,Engine_Type,Transmission,Price_INR,Price_Lakh,Mileage
0,1,Toyota,Scorpio,Petrol,Automatic,2736015,27.36015,18.0
1,2,Honda,Corolla,Electric,Automatic,3358822,33.58822,20.0
2,3,Toyota,Creta,Diesel,Automatic,3300087,33.00087,NaN
3,4,Tata,Creta,Petrol,Automatic,1234955,12.34955,15.0
4,5,Kia,X5,Petrol,Manual,3146261,31.46261,22.0

In [28]:
# using group by
import pandas as pd

df = pd.read_csv("car_dataset_100.csv")
df.groupby("Company")["Price_INR"].mean()

Company
Audi             3.024544e+06
BMW              2.961100e+06
Ford             3.071579e+06
Honda            2.733152e+06
Hyundai          2.940440e+06
Kia              2.196361e+06
Mahindra         3.365215e+06
Mercedes-Benz    3.059721e+06
Tata             2.046813e+06
Toyota           2.057103e+06
Name: Price_INR, dtype: float64